### ISSUE TITLE
setImmediate is not defined

### ISSUE THREAD

**Issue by hayesm** [fangli/kibana-authentication-proxy#17]
Hi 

I am having the following exception when I connect to the proxy:

Server starting...
Info: HTTP Basic Authentication applied
Warning: No Google OAuth2 presented
Warning: No CAS authentication presented
Server listening on 8983

ReferenceError: setImmediate is not defined
    at MemoryStore.get .../kibana-authentication-proxy-elastic/node_modules/express/node_modules/connect/node_modules/express-session/session/memory.js:41:3)
    at Object.session [as handle](.../kibana-authentication-proxy-elastic/node_modules/express/node_modules/connect/node_modules/express-session/index.js:329:11)
    at next (.../kibana-authentication-proxy-elastic/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Object.cookieParser [as handle](.../kibana-authentication-proxy-elastic/node_modules/express/node_modules/connect/node_modules/cookie-parser/index.js:46:5)
    at next (.../kibana-authentication-proxy-elastic/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Object.expressInit [as handle](.../kibana-authentication-proxy-elastic/node_modules/express/lib/middleware.js:30:5)
    at next (.../kibana-authentication-proxy-elastic/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Object.query [as handle](.../kibana-authentication-proxy-elastic/node_modules/express/node_modules/connect/lib/middleware/query.js:45:5)
    at next (.../kibana-authentication-proxy-elastic/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Function.app.handle (.../kibana-authentication-proxy-elastic/node_modules/express/node_modules/connect/lib/proto.js:201:3)

I am using the default configuration settings for all properties except:

```
"listen_port": 9300,
"enable_basic_auth": true,
"which_auth_type_for_kibana_index": "basic", // google, cas or basic
"enable_basic_auth": true,
```

Am I missing a configuration step?

**Comment by hayesm** [comment]
I am able to get past the exception by manually installing set-immediate using npm then modifying app.js to have:
     var setImmediate = require('setimmediate');

The machine is running node version 0.10.26.

**Comment by fangli** [comment]
Hi, I'll check if there are breaking changes in some special nodejs version.

**Comment by fangli** [comment]
I will not take action until get more relevant feedback from others since you have it resolved already.

**Comment by hayesm** [comment]
Agreed.

**Comment by fangli** [comment]
Thanks for your feedback anyway.
