### ISSUE TITLE
App crashes when I try to connect to it over browser

### ISSUE THREAD

**Issue by arnoblalam** [fangli/kibana-authentication-proxy#30]
Hi:

I followed the instructions on the github page. When I run "node app.js" I get the follwing:

➜  kibana-authentication-proxy git:(master) ✗ node app.js                   

```
Server starting...
Warning: No basic authentication presented
Warning: No Google OAuth2 presented
Warning: No CAS authentication presented
Server listening on 9201

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write after end
    at writeAfterEnd (_stream_writable.js:133:12)
    at Gzip.Writable.write (_stream_writable.js:181:5)
    at ServerResponse.res.write (/Users/arnoblalam/tests/kibana-authentication-proxy/node_modules/express/node_modules/connect/node_modules/compression/index.js:86:18)
    at ServerResponse.res.end (/Users/arnoblalam/tests/kibana-authentication-proxy/node_modules/express/node_modules/connect/node_modules/express-session/index.js:237:21)
    at Gzip.<anonymous> (/Users/arnoblalam/tests/kibana-authentication-proxy/node_modules/express/node_modules/connect/node_modules/compression/index.js:177:13)
    at Gzip.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)
```

Could you please help troubleshoot this issue

**Comment by adamblanchard** [comment]
It looks like the express package has a new release which causes the above. Hardcode 'express' in packages.json to 3.12.0 and it should work.

**Comment by woolfie** [comment]
I get the same error and hardcoding 'express' to 3.12.0 in packages.json had no effect. Any other ideas?

**Comment by adamblanchard** [comment]
What version of express is shown when you run `npm list`? After hardcoding to 3.12.0 you will have to reinstall the package by running `npm install` (if you haven't already).

**Comment by woolfie** [comment]
Running `npm install` fixed it, thanks. It's running OK now.

**Comment by rosstimson** [comment]
I just encountered this bug too, hardcoding to 3.12.0 and running `npm install` again fixed it for me.  Thanks a lot guys!  Looking forward to this being fixed properly.

**Comment by Vineeth-Mohan** [comment]
Same for me too. Thanks for the solution.
