### ISSUE TITLE
Not able to configure CAS server 

### ISSUE THREAD

**Issue by Vineeth-Mohan** [fangli/kibana-authentication-proxy#33]
I am seeing this error after trying to authenticate using CAS server.

Can you shed some light on what this is ?

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: 139765183436608:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:../deps/openssl/openssl/ssl/s23_clnt.c:762:

```
at SlabBuffer.use (tls.js:232:18)
at CleartextStream.read [as _read] (tls.js:452:29)
at CleartextStream.Readable.read (_stream_readable.js:320:10)
at EncryptedStream.write [as _write] (tls.js:366:25)
at doWrite (_stream_writable.js:226:10)
at writeOrBuffer (_stream_writable.js:216:5)
at EncryptedStream.Writable.write (_stream_writable.js:183:11)
at write (_stream_readable.js:582:24)
at flow (_stream_readable.js:591:7)
at Socket.pipeOnReadable (_stream_readable.js:623:5)
```

**Comment by Vineeth-Mohan** [comment]
My fix - 

Add following to app.js

https.globalAgent.options.secureProtocol = 'SSLv3_method';
https.globalAgent.options.rejectUnauthorized = false;
