### ISSUE TITLE
Kibana UI doesn't fully load

### ISSUE THREAD

**Issue by wjimenez5271** [fangli/kibana-authentication-proxy#35]
After authenticating with google auth, I'm redirected to the kibana screen which doesn't fully load. The log mentions: 

```
Server starting...
Info: HTTP Basic Authentication applied
Warning: No Google OAuth2 presented
Warning: No CAS authentication presented
Server listening on 9201

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write after end
    at writeAfterEnd (_stream_writable.js:133:12)
    at Gzip.Writable.write (_stream_writable.js:181:5)
    at ServerResponse.res.write (/opt/elk/kibana-authentication-proxy/node_modules/express/node_modules/connect/node_modules/compression/index.js:93:18)
    at ServerResponse.res.end (/opt/elk/kibana-authentication-proxy/node_modules/express/node_modules/connect/node_modules/express-session/index.js:252:21)
    at Gzip.<anonymous> (/opt/elk/kibana-authentication-proxy/node_modules/express/node_modules/connect/node_modules/compression/index.js:208:13)
    at Gzip.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)
```

**Comment by AnonymMan** [comment]
I had met the same problems,
Server starting...
Info: HTTP Basic Authentication applied
Warning: No Google OAuth2 presented
Warning: No CAS authentication presented
Server listening on 9201

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write after end
    at writeAfterEnd (_stream_writable.js:133:12)
    at Gzip.Writable.write (_stream_writable.js:181:5)
    at ServerResponse.res.write (/data/OTA/logstash/kibana-authentication-proxy/node_modules/express/node_modules/connect/node_modules/compression/index.js:93:18)
    at ServerResponse.res.end (/data/OTA/logstash/kibana-authentication-proxy/node_modules/express/node_modules/connect/node_modules/express-session/index.js:252:21)
    at Gzip.<anonymous> (/data/OTA/logstash/kibana-authentication-proxy/node_modules/express/node_modules/connect/node_modules/compression/index.js:208:13)
    at Gzip.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

**Comment by yang66** [comment]
please see pull request #31
