### ISSUE TITLE
Problems with node and Error.Forbidden

### ISSUE THREAD

**Issue by wrathchylde** [fangli/kibana-authentication-proxy#51]
Hello, 

I have migrated a known working instance of kibana-authentication-proxy between similar Ubuntu systems on EC2, and on the new host when I try to start node with app.js I get the following error accessing the port. Can you advise me please I'm having trouble finding resources.

Error: Forbidden
   at SendStream.error (/mnt/apps/kibana-authentication-proxy/node_modules/express/node_modules/send/index.js:239:16)
   at SendStream.pipe (/mnt/apps/kibana-authentication-proxy/node_modules/express/node_modules/send/index.js:425:19)
   at Object.serveStatic [as handle](/mnt/apps/kibana-authentication-proxy/node_modules/express/node_modules/connect/node_modules/serve-static/index.js:107:12)
   at next (/mnt/apps/kibana-authentication-proxy/node_modules/express/node_modules/connect/lib/proto.js:169:15)
   at Object.compression [as handle](/mnt/apps/kibana-authentication-proxy/node_modules/express/node_modules/connect/node_modules/compression/index.js:217:5)
   at next (/mnt/apps/kibana-authentication-proxy/node_modules/express/node_modules/connect/lib/proto.js:169:15)
   at pass (/mnt/apps/kibana-authentication-proxy/node_modules/express/lib/router/index.js:110:24)
   at Router._dispatch (/mnt/apps/kibana-authentication-proxy/node_modules/express/lib/router/index.js:173:5)
   at Object.router [as handle](/mnt/apps/kibana-authentication-proxy/node_modules/express/lib/router/index.js:33:10)
   at next (/mnt/apps/kibana-authentication-proxy/node_modules/express/node_modules/connect/lib/proto.js:169:15)

**Comment by wrathchylde** [comment]
I found the problem on my own. Unlike before where the answer was to issue npm update and install, in this case it was to actually remove the npm version and use the apt-get version first. Now, it's working. Thank you.
