### ISSUE TITLE
Google authenticator

### ISSUE THREAD

**Issue by AndreaCrotti** [fangli/kibana-authentication-proxy#58]
I just wanted to try the google authentication, so I followed the instructions:
- created a new project in google developer apps
- set the right client_id/client_secret and enabled google authentication.

I get the right initial screen to select which account to use and after that it fails with this error:

```
Error
   at Strategy.OAuth2Strategy.parseErrorResponse (/home/andrea/code/kibana-authentication-proxy/node_modules/passport-oauth2/lib/strategy.js:329:12)
   at Strategy.OAuth2Strategy._createOAuthError (/home/andrea/code/kibana-authentication-proxy/node_modules/passport-oauth2/lib/strategy.js:376:16)
   at /home/andrea/code/kibana-authentication-proxy/node_modules/passport-oauth2/lib/strategy.js:166:45
   at /home/andrea/code/kibana-authentication-proxy/node_modules/oauth/lib/oauth2.js:191:18
   at passBackControl (/home/andrea/code/kibana-authentication-proxy/node_modules/oauth/lib/oauth2.js:132:9)
   at IncomingMessage.<anonymous> (/home/andrea/code/kibana-authentication-proxy/node_modules/oauth/lib/oauth2.js:157:7)
   at emitNone (events.js:91:20)
   at IncomingMessage.emit (events.js:188:7)
   at endReadableNT (_stream_readable.js:975:12)
   at _combinedTickCallback (internal/process/next_tick.js:80:11)
```

Any idea about what that could be?
Thanks

**Comment by AndreaCrotti** [comment]
And by the way I got this initially using version 5.3 of kibana, then I downgraded to the original version shipped with this project but still get the same error.
This error doesn't seem to be related with Kibana though anyway from my understanding..
